### ISSUE TITLE
Cannot warn-ban Player via Console

### ISSUE THREAD

**Issue by FunnyBuddys** [robske110/BanWarn#16]
I can´t warn a player with 10 points via Console (Player will be banned auto.) 
# Here the Console LOG

Notice: Undefined variable: player in phar:///root/FC/mcpe/plugins/BanWarn_v1.2.1_deu.phar/src/robske_110/BanWarn/Main.php on line 339
[18:29:00] [Server thread/INFO]: An unknown error occurred while attempting to perform this command

**Comment by robske110** [comment]
Thanks for the report!
You can view this issue as a display issue, the player is being banned and no other problems should arise. Will fix this notice msg in the next release though.

This is due to you disabling IP-Ban, not your fault though, i forgot to test BanWarn if it is turned off. You could just turn it on, until i fix this issue
